import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/start-here',
        'getting-started/what-is-the-ga4gh-reference-cloud',
        'getting-started/registration-and-login',
        'getting-started/requesting-access-to-datasets',
        'getting-started/obtaining-a-passport-token',
        'getting-started/exploring-datasets',
      ],
    },
    {
      type: 'category',
      label: 'Interactive Demos',
      items: [
        'interactive-demos/intro-to-interactive-demos',
        'interactive-demos/explore-1000-genomes-data-via-drs-api',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/deploying-the-reference-cloud',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/api-reference-overview',
        'api-reference/drs-api-reference',
      ],
    },
  ],
};

export default sidebars;
